from __future__ import annotations

from pydantic import BaseModel, Field


class AnswerClaimOutput(BaseModel):
    """
    LLM-generated answer claim.

    This is an external LLM output schema.
    It is intentionally separate from the internal AnswerClaim class.
    """

    claim_id: str = Field(
        description="Unique identifier for the answer claim."
    )

    text: str = Field(
        description="Natural-language claim supported by the supplied reasoning."
    )

    evidence_ids: list[str] = Field(
        description="Evidence IDs supporting this claim. Use only IDs supplied in the reasoning context."
    )

    citations: list[str] = Field(
        description="Citations supporting this claim. Use only citations supplied in the reasoning context."
    )

    claim_type: str = Field(
        description=(
            "Claim type. Must be one of: "
            "fact, factual, derived, interpretation, limitation."
        )
    )

    entity: str | None = Field(
        default=None,
        description="Relevant entity or ticker, if applicable."
    )

    metric: str | None = Field(
        default=None,
        description="Relevant metric, if applicable."
    )


class AnswerSectionOutput(BaseModel):
    """
    LLM-generated answer section.
    """

    section_id: str = Field(
        description="Unique identifier for the answer section."
    )

    title: str = Field(
        description="Section title."
    )

    claims: list[AnswerClaimOutput] = Field(
        description="Claims belonging to this section."
    )


class AnswerOutput(BaseModel):
    """
    Complete structured response generated by Qwen.
    """

    executive_summary: str = Field(
        description="Concise answer to the user's question."
    )

    sections: list[AnswerSectionOutput] = Field(
        description="Structured answer sections."
    )

    overall_citations: list[str] = Field(
        description="Citations supporting the answer overall."
    )

    limitations: list[str] = Field(
        description="Limitations explicitly supported by the supplied reasoning."
    )